ダークモードの導入（next-themeの追加）
qin-salon/qin-memo pull request #22
Opened 2021-01-20 16:55 UTC by magatakohei

## ticket

- #9

## 対応内容

- [next-theme](https://github.com/pacocoursey/next-themes)の導入
- Aboutページにダークモードに変更するセレクタを追加
- 確認用としてglobal.cssにダークモード選択時の内容を記述

## メモ

- Tailwindを導入後に以下の変更が必要なようです。

  - tailwind.config.jsで、ダークモードプロバティをクラスに設定する。

  ```
  // tailwind.config.js
  module.exports = {
    darkMode: 'class'
  }
  ```

  - テーマプロパイダの属性をクラスに設定する。

  ```
  // pages/_app.js
  <ThemeProvider attribute="class">
  ```

  - サンプル

  ```
  <h1 className="text-black dark:text-white">
  ```

Tailwind使用したことがなかったので、間違えているかもしれないです・・

## キャプチャー
![image](https://user-images.githubusercontent.com/65271262/105207779-45872a80-5b8b-11eb-815b-2afea1003503.png)

## 確認したこと

- ページ遷移した際にダークモードが反映されるか。⇨されました。
- 1度ページを閉じた後に、再度開き直した場合に閉じる前の状態が保持されているか。⇨されました。
- 同一のブラウザ複数ウィンドウでテーマを変更した際に、全てのウィンドウで変更が反映されるか。⇨されました。
- 異なるブラウザでウィンドウテーマを変更した際に、全てのブラウザに変更が反映されるか⇨**されませんでした。**
ChromeとSafariにて確認しました。

PRするのが初めてのため、他の方のものを参考にさせていただきましたが、おかしな所など教えていただきたいです！
ご確認お願よろしくお願いします！

2021-01-20 22:42 UTC, magatakohei commented
Backlogにあるやつなので、まだでした。申し訳ございません。勘違いしてましたm(..)m

2021-01-21 02:16 UTC, lightsound commented
@magatakohei 
おおー！出してしまったものは仕方ないですね！
今回は気にせず、しっかりレビューさせていただきたいと思います！
次回以降、改善していきましょう！✨
　
今To doに移行しました！
他にもPRを出したい方がいるかもなので、ちょっとだけレビューは待ちますね！
明日夜ぐらいにレビュー返信するかと思いますー✌✨

2021-01-21 03:57 UTC, magatakohei commented
@lightsound 
申し訳ありません。。
気をつけますm(..)m！

2021-01-21 08:59 UTC, lightsound commented
@magatakohei 
Tailwind CSSのPRがマージされてガッツリ変わったので、またResolveしていただけると助かります！
ガッツリコンフリクトも起きると思いますが 😅

2021-01-21 10:39 UTC, magatakohei commented
@lightsound 
了解しました。確認しながら、やってみます! :sparkles:
慣れておらず申し訳ないのですが、こちらのプルリクエスト自体は閉じればよろしいんでしょうか？

2021-01-21 10:54 UTC, lightsound commented
@magatakohei
閉じる必要はないですよ！
ローカルでマージして改めてpushする形になります。

developが先に進んでしまって、@magatakohei さんののローカルブランチ（feature/magatakohei-darkmode）が遅れている状況ですので、リモートブランチのdevelopをマージすると良いかと思います。

今回はマージ時にコンフリクトが発生するはずなので、それを解決してから再度pushする感じです！分かりづらければまた仰ってくださいね👍

2021-01-21 11:46 UTC, magatakohei commented
なるほど 🧐 　理解しました!
ありがとうございます！やってみます！

2021-01-21 23:06 UTC, magatakohei commented
@lightsound 
コンフリクト解消し、再度pushしました!
以下の作業をしました。
- about.tsxに直接書いていた、セレクタをthemeChangerSample.tsxに分割しました。かつボタンに変更しました。
- _document.tsxのbodyタグにdarkmode時のクラスを追加しました。
- layout.tsxのmainタグにdarkmode時のクラスを追加しました。
[参考にしたサイト](https://dev.to/enochndika/dark-mode-with-tailwindcss-in-next-js-2if5)

#### 迷った点
- ダークモードの時に設定されるクラスを、各タグでするべきか、_document.tsxやlayout.tsxでするべきかで迷いました。
  - _document.tsxなどでした場合⇨変更があった際に、修正点が少なく楽？
  - 各タグで設定している場合⇨コンポーネントごとに開発することを考えると、こちらの方がやりやすい？

tailwindなど含め始めて使ってみたため、的外れなこと言ってるかもしれないです。
ご確認お願いしますm(..)m

2021-01-22 05:53 UTC, lightsound requested changes
全体的に良い感じですー🙆‍♂️
`disableTransitionOnChange`入れたのも良いですね👍
2点だけご確認ください〜！

2021-01-22 05:53 UTC, lightsound commented on src/pages/_app.tsx
> +      <props.Component {...props.pageProps} />;
不要なセミコロンがあります🤣
```suggestion
      <props.Component {...props.pageProps} />
```

2021-01-22 05:53 UTC, lightsound commented on src/components/sample/themeChangerSample.tsx
> +    >
ここのclassNameは分かりやすいように改行していただいているかと思いますが、全角空白が入ってしまっているので修正の必要があるのと、もし改行などをやるとしたら何かしらプラグイン的なのを探すかと思うので、いったんはノーマルでいきましょう！

2021-01-22 06:03 UTC, lightsound reviewed
あと1点、気づいたところですー！

2021-01-22 06:03 UTC, lightsound commented on src/components/sample/themeChangerSample.tsx
> +  if (!isMounted) return null;
あと1点、
```
  const swithchTheme = () => {
    if (isMounted) {
      setTheme(theme === "light" ? "dark" : "light");
    }
  };
```
こちらと
```
if (!isMounted) return null;
```
こちらの順番を変えたら、おそらく `swithchTheme` の分岐は不要かなと思いました！👀

2021-01-22 06:05 UTC, lightsound commented
あと @reeve0930 さんも同じ内容のPRを出しているので、ちょっとDMでご連絡しますねー！
https://github.com/qin-salon/qin-memo/pull/25/files

2021-01-22 15:10 UTC, lightsound commented
https://github.com/qin-salon/qin-memo/pull/22 のPRをマージしたため、Closeします！

2021-01-22 15:10 UTC, closed without merging