サインイン画面のコーディング #42
qin-salon/qin-memo pull request #49
Opened 2021-03-13 12:33 UTC by takasaki376

# 概要
・サインイン画面作成  
・ボタンコンポーネント作成  
・SVG追加（QinMemo、Google、Appleのアイコン）  
# 補足
・「左上の戻るボタンのアイコンはheroiconsをお使いください。」とありましたが、Figmaにはなかったので使ってません。
・ボタンコンポーネントは他の画面でも使う事を意識していますが、問題なければabout.tsxにテスト用のコーディングを兼ねて、サンプルを記述したいです。確認用ですが、ログアウトのアイコンもSVGは作成しているので、about.tsxをpushする場合は一緒にログアウトのアイコンもpushします。

2021-03-14 01:20 UTC, lightsound commented
ありがとうございますー！
実はもうちょっとだけ設定しようかと思っていたのですが早いのも歓迎です！😁

レビューさせていただきますね🙏

2021-03-14 01:24 UTC, lightsound commented
色んなファイルでESLintがerrors, warningを出しているのですが、おそらくESLintが効いていないですかね？またはVSCodeじゃなかったりしますか？👀

VSCodeであればこちらの拡張機能を入れていただき、まずはLintの修正をお願いしたいです🙏
[ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

こちら`yarn lint:eslint`で確認できます👍

![image](https://user-images.githubusercontent.com/8220973/111054347-43688a80-84af-11eb-9404-13267a725d25.png)

2021-03-14 01:32 UTC, takasaki376 commented
ESLintが入ってませんでした。
`yarn lint:eslint`でエラーも確認できましたので、見直してpushします。

2021-03-14 01:54 UTC, lightsound commented
typeとinterfaceですが個人的にはtypeを好んでいるのでtypeに統一したいです。

正直私もそこまで詳しくないのですが、interfaceはextendsがあるぐらいで、typeでも交差型`&`で代用できます。一方でinterfaceはオブジェクトと関数の型宣言しか使えなかったり、MappedTypesが使えなかったりと制約が多いです。

速度的にinterfaceの方が早いという話も出てましたが、TypeScriptのコンパイラ側の解決待ちだと思うので、個人的にinterfaceを使う利点はそんなに無いと考えています🤔

2021-03-14 02:09 UTC, lightsound commented on src/components/share/Button.tsx
> +  onClick?: (e: React.MouseEvent<HTMLElement>) => void;
結果は一緒なんですけど下記の方が自己定義が少なくて良さそうです。

```
onClick: DOMAttributes<HTMLButtonElement>["onClick"]
```

2021-03-14 02:33 UTC, lightsound requested changes
他にもまだありそうなのですが、いったん修正が上がってから再度見させてください〜！🙏

2021-03-14 02:33 UTC, lightsound commented on src/components/share/Button.tsx
> +}
ここはUnion Types（`|`）とType Guardを使って出し分けをして欲しいです。

下記のようになります。

```
type Common = {
  id: string;
  color?: "blue" | "red" | "black" | "white" | "gray" | "orange";
  textColor?: "black" | "red" | "blue";
  disabled?: boolean;
  children?: ReactNode;
  className?: string;
  StartIcon?: React.VFC;
  EndIcon?: React.VFC;
  size?: "large" | "small";
};

type Button = Common & {
  type: "button";
  onClick: DOMAttributes<HTMLButtonElement>["onClick"];
};

type Link = Common & {
  type: "link";
  linkProps: string;
};

const isButton = (props: Button | Link): props is Button => {
  return "onClick" in props;
};
```

そしてComponent内で、isButtonを使ってButtonかLinkかの出し分けをする感じですね😁

2021-03-14 02:33 UTC, lightsound commented on src/components/share/Button.tsx
> +const Button: React.FC<Props> = (props) => {
Reactはたしか次期バージョンのv18からexportされなくなるはずなので、Reactからチェーンするのではなく直接importしてください！

また`FC`も今後のアップデートで非推奨になるはずなので`VFC`を使ってください！（VFCがFC相当になるみたいな話だった気がするのですが、そのときに一括置換したらいいかなと）

2021-03-14 02:33 UTC, lightsound commented on src/components/share/Button.tsx
> +const Button: React.FC<Props> = (props) => {
ググったら速攻出てきました笑
まさにこれと同じ意見です
https://ikesyo.hatenablog.com/entry/2020/12/18/141737

2021-03-14 02:33 UTC, lightsound commented on src/components/share/Button.tsx
> +    " my-4 mx-auto  rounded-full focus:outline-none flex flex-row justify-center ",
不要なスペースを削除してください👍

2021-03-14 02:33 UTC, lightsound commented on src/pages/signin.tsx
> +        <div className="h-screen flex flex-col justify-center  ">
不要なスペースを削除してください👍

2021-03-14 02:36 UTC, lightsound commented
左上のアイコンはheroiconsをというのはこちらの「＜」アイコンのことです！（分かりづらい笑）

![image](https://user-images.githubusercontent.com/8220973/111055471-79ab0780-84b9-11eb-9697-3a368ebed242.png)

2021-03-14 02:41 UTC, lightsound commented
> ボタンコンポーネントは他の画面でも使う事を意識していますが、問題なければabout.tsxにテスト用のコーディングを兼ねて、サンプルを記述したいです。確認用ですが、ログアウトのアイコンもSVGは作成しているので、about.tsxをpushする場合は一緒にログアウトのアイコンもpushします。


こちらaboutへ記述するのは使うのは問題ございません。たくさんの用途を想定されていて素晴らしいです（他の方も助かると思います）が、最後のリリース前のリファクタで、バンドルサイズ削減のために必要なかったpropsは見直しさせていただければと思います👍👍

2021-03-14 08:29 UTC, takasaki376 commented
修正が完了しましたので、ご確認よろしくお願い致します。

>お、Figmaにないですか？👀
>自分の方では見えており下記画像の「＜」アイコンを想定しています！

Desctopのページを見ていました。Mobileのページを確認してアイコンを追加しています。

2021-03-15 02:44 UTC, lightsound requested changes
ちょっと多めになってしまいましたが、いったんこちらの修正をお願いします🙏

2021-03-15 02:44 UTC, lightsound commented on src/components/icon/SigninOut.tsx
> +    </svg>
デザインに一貫性を持たせるためにアイコンは[heroicons](https://heroicons.com/)に統一していただきたいです。「logout」があるのでそちらをお使いください！[heroicons](https://heroicons.com/)にない場合に他の代替手段を考える感じですね！
![image](https://user-images.githubusercontent.com/8220973/111095217-54cd9780-8580-11eb-85e6-07edda5dc12c.png)

2021-03-15 02:44 UTC, lightsound commented on src/components/icon/SigninOut.tsx
> +    </svg>
またファイル名が`SigninOut`となっているので`SignOut`に変えていただけるといいかな〜と😁

2021-03-15 02:44 UTC, lightsound commented on src/components/share/Button.tsx
> +  color?: "blue" | "red" | "black" | "white" | "gray" | "orange" | "transparent";
`bgColor`という名前がいいかなーと思いました！👀

何のcolorかを明示的にしたいのと、Tailwindが`bg-red-400`とか`text-blue-200`とかで指定するので！

2021-03-15 02:44 UTC, lightsound commented on src/components/share/Button.tsx
> +  EndIcon?: VFC<any | undefined>;
名前はキャメルケース`startIcon`がいいですね〜

また親での呼び出しも
```
startIcon={<FooIcon />}
```
のように指定する方がpropsを渡せるので良いです。

詳しくはMaterial-UIやChakra-UIなども参考にしてみてください〜！🙏
・https://material-ui.com/components/buttons/#buttons-with-icons-and-label
・https://chakra-ui.com/docs/form/icon-button

2021-03-15 02:44 UTC, lightsound commented on src/components/share/Button.tsx
> +  };
こちらはコンポーネントの外に出してください😎
コンポーネントのレンダリング毎に毎回呼び出されてしまうので〜！

2021-03-15 02:44 UTC, lightsound commented on src/components/share/Button.tsx
> +  };
またこちら、`"foo" in props`を紹介してしまいましたが、今回はtypeをもたせているので下記のように判断させることも可能です。
```
props.type === "button"
```

ちなみにGameHintではtypeは持たせてなくて、buttonというpropsをbooleanで持たせています。そちらのほうが毎回typeを指定する必要がないのでオススメです。

```
type Common = {
  children: ReactNode;
  className?: string;
  coloredTextDefault?: boolean;
  disable?: boolean;
};

type ClickButton = Common & { button: boolean; onClick?: DOMAttributes<HTMLButtonElement>["onClick"] };
type LinkButton = Common & { linkProps: LinkProps; external?: boolean };

export const isClickButton = (props: ClickButton | LinkButton): props is ClickButton => {
  return "button" in props;
};
```

2021-03-15 02:44 UTC, lightsound commented on src/components/share/Button.tsx
> +        >
ここHTML要素はbuttonタグでお願いします。buttonでないとアクセシビリティが非常に悪くなります😱

専門家ではないので`role="button"`で解決するのか分かりませんが、spanにしている理由ってありますか？

2021-03-15 02:44 UTC, lightsound commented on src/components/share/Button.tsx
> +        >
また`data-testid`は必要がなければ要らないと思っていますがいかがでしょうか？😁

2021-03-15 02:44 UTC, lightsound commented on src/components/share/Button.tsx
> +          <span data-testid={props.id} role="link" className={classes}>
ここも同様にaタグでいけるのであればaタグが良いです！

2021-03-15 02:44 UTC, lightsound commented on src/pages/signin.tsx
> +  };
ここは先ほどのisButtonの指定を修正したら不要になるはずです✌

2021-03-15 13:42 UTC, ippo012 approved these changes
LGTM!!!

2021-03-15 13:42 UTC, lightsound approved these changes
いくつかライブコーディングで一緒に修正しました😁

2021-03-15 13:42 UTC, merged