Feature/aluco hirata
qin-salon/qin-memo pull request #57
Opened 2021-03-25 16:55 UTC by aluco-hirata

# 概要
・アカウント連携のセッティング画面のコーディング
・SVG追加（Qinアカウントのアイコン）

# 概要
appleアイコンのpathにfill whiteがあり、class名からの色変更ができませんでした。
その他headerあたりも、コンポーネント化したいですが、現状未着手です。
いろいろ初めてなので、恐る恐るやってみました。。。

2021-03-26 01:47 UTC, lightsound requested changes
こちらご確認をお願いいたします😁

2021-03-26 01:47 UTC, lightsound commented on src/pages/settings/account.tsx
> +          <Button button id="" bgColor="blue" className="my-0 mx-0 text-xs">
ここ、そもそもButtonコンポーネントのidが不要ですね。前回のレビューで見切れていない部分でした。Buttonコンポーネントのidごと削除でお願いします🙏

2021-03-26 01:47 UTC, lightsound commented on src/pages/settings/account.tsx
> +            <AppleIcon className="fill-current" />
こちらAppleIconが白くて見えないですね😂笑

AppleIconを白か黒か設定できるようにお願いしても良いですか？👀

2021-03-26 01:47 UTC, lightsound commented on src/pages/settings/account.tsx
> +          <Button button id="backButton" bgColor="transparent" className="absolute left-0 top-0 mx-0 my-0 px-0 py-3.5">
同様にid削除で🙏

2021-03-26 01:47 UTC, lightsound commented on src/pages/settings/account.tsx
> +          <Button button id="" bgColor="gray" className="my-0 mx-0 text-xs">
同様にid削除で🙏

2021-03-26 01:49 UTC, lightsound commented
iPhoneSEなどで見た場合に、余白が無くパツパツになっちゃいます。
レスポンシブ対応は横幅320pxまで考慮した方がいいので、こちらも修正をお願いします！
（特にC向けのプロダクトだと幅広いユーザーを想定したレスポンシブ対応が必要ですね！）

![image](https://user-images.githubusercontent.com/8220973/112565618-b9121600-8e20-11eb-9519-6a6c3a95dbd3.png)

2021-03-26 10:11 UTC, aluco-hirata commented on src/pages/settings/account.tsx
> +            <AppleIcon className="fill-current" />
ありがとうございます！

こちら、AppleIcon.tsxのpathからfill="white"削除でいけるかと思いますが、
他ページへの影響ある場合は、そちらも修正したほうがいいでしょうか？？

あとfigmaのデザイン変わってたりしますか？？（昨日見てたデザインと違うようなので。。。）

2021-03-26 10:57 UTC, lightsound commented on src/pages/settings/account.tsx
> +            <AppleIcon className="fill-current" />
> こちら、AppleIcon.tsxのpathからfill="white"削除でいけるかと思いますが、他ページへの影響ある場合は、そちらも修正したほうがいいでしょうか？？

propsを渡してblackかwhiteか決められるとありがたいです😆

> あとfigmaのデザイン変わってたりしますか？？（昨日見てたデザインと違うようなので。。。）

変わりえます。ただおそらく昨日から変化はないように思うので、アプリ版を見てたとかではないでしょうか・・・？ただし先ほど確認したところアプリ版を正としたいので、現状やっていただいたデザインであっております 💯 

アプリ版
https://www.figma.com/file/Yln6ROWrgXJXZN5FcApO68/Qin-Memo?node-id=2123%3A947

Webスマホ版
https://www.figma.com/file/Yln6ROWrgXJXZN5FcApO68/Qin-Memo?node-id=1370%3A5412

2021-03-26 16:16 UTC, aluco-hirata commented
いただいた修正指示反映しましたので、ご確認お願いします！

2021-03-28 02:06 UTC, lightsound approved these changes, later dismissed
修正確認しました！
🙆🏼‍♂️ だったのでマージします！
ナイスPRをありがとうございました👍👍

2021-03-28 05:36 UTC, lightsound commented
他のButtonコンポーネントでid周りでエラー出しててデプロイがこけてたので、そこだけ[私の方で修正](https://github.com/qin-salon/qin-memo/pull/57/commits/56793cb4fff7e6040c9ae50280a0b5a5739699ad)しました👍

マージしますねー

2021-03-28 05:36 UTC, lightsound approved these changes

2021-03-28 05:36 UTC, merged

2021-03-28 07:28 UTC, aluco-hirata commented
ありがとうございます！