ユーザーのメモ一覧画面のコーディング
qin-salon/qin-memo pull request #58
Opened 2021-03-26 15:03 UTC by takasaki376

# 概要

- メモ一覧画面作成
- テキストボックスのコンポーネント作成
- アバターのコンポーネント作成

# 補足

- ヘッダコンポーネント、カードコンポーネントは他の画面でも使用する想定で、コンポーネントにしました。
- ボタンコンポーネントのサイズを追加しています。
- 他の方のプルリクでボタンコンポーネントのid削除とあったので、私の方でも削除しています。
- データの取得はyarn dev だと取得できますが、yarn build → start だと取得できません。（非同期タブと同様の結果なので、mswの動作がわからず諦めました。）
- noteの３行目にある「むかしむかし、足柄山に～」に改行コードがないのは、改行コード無しで登録された場合のテストであえて残しています。

2021-03-26 23:05 UTC, takasaki376 commented
ボタンサンプルの所に、アバター、テキストボックスのサンプルを追加しました。
タブの名前とファイル名を button.tsx → sample.tsx へ変更しています。

2021-03-28 05:50 UTC, lightsound commented
@takasaki376 
PRありがとうございますー！しかしながら、先にあったPRをマージしたことによるコンフリクトが発生してしまったので、そちらの解決をお願いします🙏💦

2021-03-28 05:52 UTC, lightsound commented
@takasaki376 
PRありがとうございますー！こちらを見る前にもとのブランチの方でButtonのidを削除してしまったのでコンフリクトが発生してしまいました・・・そちらの解決をお願いします🙏💦

2021-03-28 07:13 UTC, takasaki376 commented
developの内容をpullした後に、featureへpushしました。
```
git checkout develop
git pull origin develop
```
※pushの操作はVScodeの画面から実行しています。

pullすると、signin.tsxとsignup.tsxのアップルアイコンが、見えなくなりました。合わせて修正した方がよいでしょうか？
今回のプルリクのタイトルと違う修正になるため、別のプルリクとした方がよいかが判断つかないです。

2021-03-28 07:22 UTC, lightsound commented
確認します！

2021-03-28 07:53 UTC, lightsound commented
@takasaki376 
先にこちらのレビューをお願いしてもよいですか？
https://github.com/qin-salon/qin-memo/pull/61

もしご確認いただけたらApproveしていただけると！
先にそちらをマージしてから、こちらのレビューに入ります！

2021-03-28 08:55 UTC, lightsound commented
こちらPC画面からやっちゃいましたか・・？👀
実はIssue的にはスマホ画面を想定していたので😅
https://github.com/qin-salon/qin-memo/issues/44

もし可能であればレスポンシブまでお願いできたりしますか？

2021-03-28 09:00 UTC, takasaki376 commented
すいません。勘違いしていました。PCとモバイル全部見て、対応できそうな画面を選んでました。
一応、レシポンシブ対応するならどこに追加すると想像して作っているので、やってみます。後で調整すれば良いと思いますので、とりあえずlg以上（1024px）をPCとして対応します。

2021-03-28 09:24 UTC, lightsound commented
@takasaki376 
お願いします！
一応レビューは進めておきます！🙏

2021-03-28 09:51 UTC, takasaki376 commented
# 変更点
userHeader.tsxでコンポーネントを分けていましたが、[userId].tsxにまとめます。
レスポンス対応は[userId].tsxのみです。
mswで型が間違っていたので修正しました。

2021-03-29 12:53 UTC, takasaki-201070 commented
Buttonコンポーネントの修正履歴にdevelopの修正履歴がなかったので、もう一度やり直しました。
```
git checkout develop
git pull origin develop
git checkout feature/takasaki376_users
git rebase develop
```

前回の時は、git rebase develop が漏れていました。

2021-03-30 00:36 UTC, lightsound requested changes
長くなってしまいましたが、いったんこちらの修正をお願いします！
CSSの細かい調整などは最終的なリファクタリングですべて行います✨

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +const ramdom = Math.floor(Math.random() * (ramdomMax + 1 - ramdomMin)) + ramdomMin;
randomのtypo発見！笑👀

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +  return "src" in props && props.src !== "";
おそらくこれだけでいけますね！🧐
`sample.tsx`の`src=""`は消す必要があります！

```suggestion
  return "src" in props;
```

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +      "bg-purple-300": ramdom === 3,
ここって機能していますか？
動いていないように見えましたが...👀

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +        </Button>
ここはボタンとは責務を分けたいので、分離していただきたいです🥲

`Avatar`はあくまでアバターを表示するだけの機能に集中させ、もしボタンにする必要がある場合は、使いたいところで下記のようにするべきだと考えています！

```
<Button>
  <Avatar />
</Button>
```

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +        </Button>
また型的にaltが無いことは無いので、こちらの分岐は無くしていいと思います！
```
props.alt ? props.alt.substr(0, 1) : null
```

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/InputText.tsx
> +type textareaType = CommonType & {
Typeは大文字でお願いします！👍

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/InputText.tsx
> +type inputType = CommonType & {
こちらも大文字で👍👍

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +  onClick?: (e: React.MouseEvent<HTMLElement>) => void;
こちらReactからチェーンで繋ぐのではなく、直接`MouseEvent`をimportしていただきたいです！😁

`React`はたしかv18から含まれなくなるため

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/InputText.tsx
> +export const InputText: React.FC<textareaType | inputType> = (props) => {
こちらも`React`から繋ぐのではなく直接importしていただきたい＋`FC`ではなく`VFC`でimportをお願いします！

2021-03-30 00:36 UTC, lightsound commented on src/components/shared/InputText.tsx
> +  multiline?: boolean;
ここはおそらくrequiredですね！

```suggestion
  multiline: boolean;
```

2021-03-30 00:36 UTC, lightsound commented on src/components/users/MemoCard.tsx
> +  const pattarn = "(^.*)(\n)";
ここはコンポーネント外に出して変数名は大文字でお願いします！

2021-03-30 00:36 UTC, lightsound commented on src/components/users/MemoCard.tsx
> +  const title = String(excTitle ? excTitle[0] : "");
ここも関数化してコンポーネント外に出して定義したほうが良さそうです😊

2021-03-30 00:36 UTC, lightsound commented on src/components/users/MemoCard.tsx
> +            </Button>
ここホバーエフェクトが出ていますが、押せるところではないので`button`というよりは普通のタグが良いかもです！最初の段階で想定できてなくてごめんなさい🙇💦

2021-03-30 00:36 UTC, lightsound commented on src/pages/users/[userId].tsx
> +      const listNote = await fetcher<ListNote[]>(`${userUrl}/${user.id}/notes/`);
`fetch`は`async.tsx`にあるようにSWRを使っていただきたいです！

あまりfetchの自作はしたくなくライブラリに任せるか標準のfetchだけで片付けたいというのが個人的な考えです（少なくとも今回そこまで必要なほどのコードベースではないということもあり）。

2021-03-30 00:36 UTC, lightsound commented on src/pages/users/[userId].tsx
> +import { fetcher, userUrl } from "../../lib/api";
importする際は絶対パスでお願いします！
（先程のコメントからそもそも`lib/api`は要らないかなーと思っていますが💦）

2021-03-30 00:36 UTC, lightsound commented on src/pages/users/[userId].tsx
> +  const [listNote, setListNote] = useState<ListNote[]>([]);
SWRを使うとここらへんの`useState`や`useEffect`が不要になります。

2021-03-30 00:41 UTC, lightsound commented
InputとTextareaなどはそもそも複雑化する可能性が非常に高いので分けなくてもいいかもしれないとは思いました！Button・Avatarも最終的には見直す可能性があります（これはもともと私がボタンをGameHintで分けたりしていたことに起因するかとは思いますが・・・🙇💦）

QinのSimple, Fastという理念から不要なコードベース＋バンドルサイズの肥大化は避けたいと考えているため、最終的なリファクタリングで調整するかもです。今は残しておいても問題はありません🙏

2021-03-30 11:42 UTC, takasaki376 commented on src/components/shared/Avatar.tsx
> +  return "src" in props && props.src !== "";
削除すると下記のようになってしまいました。こちらは修正せずに進めます。
![image](https://user-images.githubusercontent.com/75880059/112983222-60cc7280-9198-11eb-8990-128c3177d1bf.png)

2021-03-30 11:44 UTC, takasaki376 commented on src/components/shared/Avatar.tsx
> +      "bg-purple-300": ramdom === 3,
`export const Avatar`より上にあるので、リロードしたタイミングで値が決まっていると思います。
こんなのでできるのかなという遊びで試しに入れてみたコードなので、消しても構いません。

2021-03-30 11:54 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +      "bg-purple-300": ramdom === 3,
なるほどですー！
そしたらここはいまいま必要では無いと思うのでいったん消しましょう！✊

2021-03-30 13:34 UTC, lightsound commented
@takasaki376 
他のPRをマージしたりとdevelopが先に進んでしまったので、ちょうど良いタイミングでPullしておいてくださいませ🙏

2021-03-31 15:13 UTC, takasaki376 commented
devlopブランチのマージが完了しました。
指摘に対する修正のコミットは
- fetchの型指定削除
- レスポンシブデザイン対応
- Avatarコンポーネントから不要コード削除
- useSWRを使用するように修正
の４点です。

devlopマージ後の修正は
- 他の画面の修正を反映
- textareaのスタイル微調整
の２点です。

2021-04-01 14:01 UTC, lightsound requested changes
再度、こちらご確認くださいませー🙏

2021-04-01 14:01 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +  return "src" in props && props.src !== "";
sample.tsxのsrc=""は消されましたか？
そちらを消すとうまく動くかと思います！

2021-04-01 14:01 UTC, lightsound commented on src/components/shared/Avatar.tsx
> +  onClick?: (e: React.MouseEvent<HTMLElement>) => void;
こちらMouseEventをimportして使っていただきたいです！
`React.`で繋ぐやり方自体を削除したいということです！🙏

2021-04-01 14:01 UTC, lightsound commented on src/components/shared/InputText.tsx
> +  multiline?: boolean;
こちらもご確認お願いします！

2021-04-01 14:01 UTC, lightsound commented on src/components/users/MemoCard.tsx
> +  const title = getTitle(excTitle);
`excTitle`は以降で使われていないので、getTitleのロジックに含めても良いかなと思いました！🤔

2021-04-01 14:16 UTC, takasaki376 commented on src/components/users/MemoCard.tsx
> +  const title = getTitle(excTitle);
sample.tsxのsrc=""は、実際のソースで`src=user.avatarUrl`のように記述されて、user.avatarUrlの値が空白になっている場合を想定しています。サンプルなので、変数の代わりに直接値を指定しています。

新規登録時はsrcを指定しないと思いますが、アバター登録せずにそのままユーザ作成を行った場合の想定です。

2021-04-01 14:37 UTC, lightsound commented on src/components/users/MemoCard.tsx
> +  const title = getTitle(excTitle);
@takasaki376 
なるほどです！
その場合、null or undefinedを一緒に考慮してもいいとは思うので、`!props.src`での指定の方が良いですかね・・・？👀

2021-04-01 15:46 UTC, takasaki376 commented
修正完了しました。レビューをお願いします。

# 変更点

- ‘React.`を削除しました。
- アバターコンポーネントでsrcに値がなかった場合の条件式を変更しました。（Avator.tsx）
- アバターコンポーネントのsrcの型を変更してnullを受け取れるようにしました。
- サンプルにあるアバターのsrcの値を変更しました。
- sample.tsxを見て、「公開中」はボタンコンポーネントから不要になったので削除しました。
- 最初の指摘内容を見直して、対応漏れていたmultilineの型を変更しています。

2021-04-02 01:33 UTC, lightsound commented
@takasaki376 
🙆🏼‍♂️ でしたー！！
大きめな修正もたくさんしてくださってありがとうございます😭
マージしておきます 🔀

2021-04-02 01:33 UTC, lightsound approved these changes

2021-04-02 01:34 UTC, merged