:tada:
qin-salon/qin-memo pull request #59
Opened 2021-03-28 04:03 UTC by kondo-tomonori1001

#43 

# 概要
- プロフィール設定画面のコーディング

# 補足
- 分からないことだらけですが、せっかくの機会なのでチャレンジしてみました！
- コンテンツの幅はlayoutとかで全体を指定されるのかな？と思いましたが、見た目を確認するために幅を設定して中央寄せしました。
- 背景色やフォントカラーはtailwindで細かく指定する方法が分からなかったので、適当なものを指定しました。
- 初めてのPRで間違いなど多々あるかと思いますが、どうぞよろしくお願いします🙇‍♂️

2021-03-29 12:22 UTC, lightsound commented
PRありがとうございます！😁✨
明日見させていただきますー！！🙏

2021-03-30 01:45 UTC, lightsound requested changes
下記点の修正をお願い致します🙇

色やサイズ感の調整は最終的に行う予定です！
基本的には見た目通りで素晴らしいなと思いました😁

2021-03-30 01:45 UTC, lightsound commented on src/pages/settings/index.tsx
> +import { InputText, inputText } from "src/components/shared/InputText";
ここのinputTextが宣言されていないのにimportされちゃってます！
不要かと思うので削除をお願いします！

2021-03-30 01:45 UTC, lightsound commented on src/pages/settings/index.tsx
> +            id="iconChangeBtn"
他の型のPull Reqestsで現在のdevelopは少し更新されてしまっていましてButtonコンポーネントのidは不要になりました。こちら削除をお願いします🙏

2021-03-30 01:45 UTC, lightsound commented on src/pages/settings/index.tsx
> +      <Button button id="startBtn" className="w-full">
ここのidも👍

2021-03-30 01:45 UTC, lightsound commented on src/pages/settings/index.tsx
> +      <Button button id="endBtn" bgColor="gray" textColor="black" className="w-full">
ここのidも👍

2021-03-30 01:55 UTC, lightsound commented
実はなんですが @kondo-tomonori1001 さんがやっていただいた画面のデザインとURLパスが違っています😂笑

- `pages/registration.tsx` → [初回登録時のプロフィール設定画面](https://www.figma.com/file/Yln6ROWrgXJXZN5FcApO68/Qin-Memo?node-id=1326%3A0)
- `pages/settings/index.tsx` → [登録完了後に行うプロフィール設定画面](https://www.figma.com/file/Yln6ROWrgXJXZN5FcApO68/Qin-Memo?node-id=1314%3A324)

もし可能であれば下記対応もお願いできますか？

- `settings/index.tsx`の内容を`registration.tsx`でも使えるようにコンポーネント化する
- `settings/index.tsx`を修正する
- `registration.tsx`も完成させる

厳しいようでしたら問題ありません😁
私と一緒にライブコーディングで行うでも問題ないので仰ってください👍

2021-03-30 12:33 UTC, kondo-tomonori1001 commented
しまぶーさん！確認頂きありがとうございました🙇‍♂️
こうやって見て頂けるのはとても有難いし、貴重な経験です。。。😭

そして、すみません。。URL間違ってましたね笑😂


ご指摘いただいた分を一通り修正してみたので、再度ご確認をお願いします！

2021-03-30 13:20 UTC, lightsound approved these changes
画面共有して一緒にリファクタリングしました！

2021-03-30 13:21 UTC, merged